app:
  environment: dev
  addr: 0.0.0.0:8080
postgres:
  addr: localhost:5432
  name: crypto
  user: postgres
  pass: postgres
  pool: 10
cryptoWallet:
  endpoint: https://hackathon.lsp.team/hk
rateLimiter:
  rate: 1s
  burst: 1
  expiresIn: 1m
